### ISSUE TITLE
Ctrl + c give one error

### ISSUE THREAD

**Issue by patrickalin** [patrickalin/bloomsky-client-go#12]
Est-ce normal ?

main.collect.func1(0xc4201c6400)
	/Users/pa/go/src/github.com/patrickalin/bloomsky-client-go/main.go:229 +0xc8
created by main.collect
	/Users/pa/go/src/github.com/patrickalin/bloomsky-client-go/main.go:231 +0x118

**Comment by tixu** [comment]
Je pense que c'est corrigé par contre il prend trop d'événement
