### ISSUE TITLE
Bug major : Problem if refresh of the web page

### ISSUE THREAD

**Issue by patrickalin** [patrickalin/bloomsky-client-go#15]
Si je rafraichi la page, le JSON retourné est vide. Je ne trouve pas pourquoi.
Si ensuite tu attends, la page reçoit le json avec le timer et donc ça refonctionne.
Je submit avec mes debugs. Je ne vois vraiment pas où est le problème.

**Comment by tixu** [comment]
Should work now ? @patrickalin  can you check?

**Comment by patrickalin** [comment]
It's ok. Thanks.
