### ISSUE TITLE
Test logfile

### ISSUE THREAD

**Issue by patrickalin** [patrickalin/bloomsky-client-go#18]
I execute the binary.
In one other console : tail -f bloomsky.log
But there is a problem on my Mac.

Logs are blocked.

Have you the same problem ?

**Comment by patrickalin** [comment]
Je commence à voir le problème si un fichier existe déjà. Il réécrit à partir du début et donc on se retrouve avec un fichier incohérent sauf si les logs sont supérieurs. Ce n'est donc pas un problème de flsuh.

**Comment by tixu** [comment]
comme tu le peux, le fichier est maintenant en append.
