### ISSUE TITLE
Documentation on generating a release

### ISSUE THREAD

**Issue by psarossy** [patrickalin/bloomsky-client-go#41]
hey @patrickalin 

Do you have documentaion you can add on how to generate a full new release? (cross compilation etc)

I'd be interested in doing a new release to pick up changes in the main branch, but don't have enough docs to do it...

Thanks a bunch!

**Comment by patrickalin** [comment]
I add in the readme some information.
There was a problem with the key between travis and github.
Each time that you tag the code, Travis build and push artefact in github.

**Comment by psarossy** [comment]
Thanks a bunch!
